"use client";

import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Minus, Plus, Trash2 } from "lucide-react";
import { useCart } from "@/components/cart-provider";

export default function CartPage() {
  const { items, subtotal, updateQuantity, removeItem } = useCart();
  const shipping = subtotal >= 100 || subtotal === 0 ? 0 : 8;
  return <div className="mx-auto max-w-7xl px-5 py-14 lg:px-10 lg:py-20"><p className="text-xs font-semibold uppercase tracking-[.2em] text-coral">Your bag</p><h1 className="mt-4 font-display text-6xl">A good start.</h1>{!items.length ? <div className="mt-16 rounded-2xl bg-sage/50 px-6 py-20 text-center"><p className="font-display text-3xl">Your bag is waiting</p><p className="mt-3 text-sm text-ink/60">Take a look around and find something you love.</p><Link href="/shop" className="mt-7 inline-flex bg-ink px-6 py-3 text-sm font-semibold text-white">Continue shopping</Link></div> : <div className="mt-12 grid gap-12 lg:grid-cols-[1fr_360px]"><div className="divide-y divide-ink/10">{items.map((item) => <div key={`${item.product.id}-${item.size}`} className="flex gap-4 py-6 first:pt-0"><div className="relative h-32 w-24 shrink-0 overflow-hidden bg-sage"><Image src={item.product.image} alt={item.product.name} fill sizes="96px" className="object-cover" /></div><div className="flex flex-1 justify-between gap-4"><div><Link href={`/shop/${item.product.slug}`} className="text-sm font-medium">{item.product.name}</Link><p className="mt-1 text-xs text-ink/50">{item.color}{item.size && ` · ${item.size}`}</p><div className="mt-5 flex items-center border border-ink/15"><button onClick={() => updateQuantity(item.product.id, item.quantity - 1, item.size)} className="p-2" aria-label="Decrease quantity"><Minus size={13} /></button><span className="w-7 text-center text-xs">{item.quantity}</span><button onClick={() => updateQuantity(item.product.id, item.quantity + 1, item.size)} className="p-2" aria-label="Increase quantity"><Plus size={13} /></button></div></div><div className="text-right"><p className="text-sm">${item.product.price * item.quantity}</p><button onClick={() => removeItem(item.product.id, item.size)} className="mt-6 text-ink/40 hover:text-ink" aria-label={`Remove ${item.product.name}`}><Trash2 size={16} /></button></div></div></div>)}</div><aside className="h-fit bg-sand p-7"><h2 className="font-display text-2xl">Order summary</h2><div className="mt-7 space-y-4 border-b border-ink/10 pb-6 text-sm"><div className="flex justify-between"><span className="text-ink/60">Subtotal</span><span>${subtotal}</span></div><div className="flex justify-between"><span className="text-ink/60">Shipping</span><span>{shipping ? `$${shipping}` : "Free"}</span></div></div><div className="flex justify-between pt-5 text-base font-semibold"><span>Total</span><span>${subtotal + shipping}</span></div><Link href="/checkout" className="mt-7 flex items-center justify-center gap-2 bg-moss py-4 text-sm font-semibold text-white">Continue to checkout <ArrowRight size={16} /></Link><p className="mt-4 text-center text-[11px] leading-5 text-ink/50">Checkout is a demo flow. No payment will be processed.</p></aside></div>}</div>;
}
