"use client";

import Link from "next/link";
import { ArrowLeft, LockKeyhole } from "lucide-react";
import { useCart } from "@/components/cart-provider";
import { useState } from "react";

export default function CheckoutPage() {
  const { items, subtotal, clearCart } = useCart();
  const [submitted, setSubmitted] = useState(false);
  if (!items.length && !submitted) return <div className="mx-auto max-w-xl px-5 py-24 text-center"><h1 className="font-display text-4xl">Your bag is empty</h1><Link href="/shop" className="mt-7 inline-block bg-ink px-6 py-3 text-sm font-semibold text-white">Browse the collection</Link></div>;
  if (submitted) return <div className="mx-auto max-w-xl px-5 py-24 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-sage text-moss">✓</div><h1 className="mt-7 font-display text-5xl">Thank you.</h1><p className="mt-4 text-sm leading-6 text-ink/60">Your demo order has been noted. In a production build, this is where a payment provider and order confirmation would take over.</p><Link href="/shop" className="mt-8 inline-block bg-ink px-6 py-3 text-sm font-semibold text-white">Continue shopping</Link></div>;
  return <div className="mx-auto max-w-6xl px-5 py-12 lg:px-10"><Link href="/cart" className="inline-flex items-center gap-2 text-xs text-ink/60"><ArrowLeft size={14} /> Back to bag</Link><div className="mt-10 grid gap-12 lg:grid-cols-[1fr_340px]"><div><h1 className="font-display text-5xl">Checkout</h1><div className="mt-8 border border-amber-700/20 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><strong>Demo mode:</strong> Payments are not connected. This form demonstrates the order flow only.</div><form onSubmit={(event) => { event.preventDefault(); clearCart(); setSubmitted(true); }} className="mt-10 space-y-7"><div><label className="text-xs font-semibold uppercase tracking-[.16em]">Email</label><input required type="email" className="mt-3 w-full border-b border-ink/20 bg-transparent py-3 text-sm outline-none focus:border-moss" placeholder="you@example.com" /></div><div><label className="text-xs font-semibold uppercase tracking-[.16em]">Shipping address</label><div className="mt-3 grid gap-4 sm:grid-cols-2"><input required className="border-b border-ink/20 bg-transparent py-3 text-sm outline-none focus:border-moss sm:col-span-2" placeholder="Full name" /><input required className="border-b border-ink/20 bg-transparent py-3 text-sm outline-none focus:border-moss sm:col-span-2" placeholder="Address" /><input required className="border-b border-ink/20 bg-transparent py-3 text-sm outline-none focus:border-moss" placeholder="City" /><input required className="border-b border-ink/20 bg-transparent py-3 text-sm outline-none focus:border-moss" placeholder="Postal code" /></div></div><button className="flex w-full items-center justify-center gap-2 bg-moss py-4 text-sm font-semibold text-white"><LockKeyhole size={16} /> Place demo order</button></form></div><aside className="h-fit bg-sand p-6"><p className="font-display text-2xl">Your order</p><div className="mt-6 space-y-4 border-b border-ink/10 pb-5 text-sm">{items.map((item) => <div key={`${item.product.id}-${item.size}`} className="flex justify-between gap-4"><span className="text-ink/60">{item.product.name} × {item.quantity}</span><span>${item.product.price * item.quantity}</span></div>)}</div><div className="flex justify-between pt-5 text-sm font-semibold"><span>Total</span><span>${subtotal}</span></div></aside></div></div>;
}
