export type Category = 'All' | 'Ceramics' | 'Textiles' | 'Woodwork' | 'Objects'
export type Product = { id:string; name:string; category:Exclude<Category,'All'>; price:number; description:string; image:string; badge?:string; details:string[] }
export const products: Product[] = [
  {id:'mori-mug',name:'Mori stoneware mug',category:'Ceramics',price:34,description:'A quietly generous cup, hand-thrown and finished in a soft mineral glaze.',image:'https://images.unsplash.com/photo-1514228742587-6b1558fcf93a?auto=format&fit=crop&w=1000&q=85',badge:'Bestseller',details:['Hand-thrown stoneware','12 oz capacity','Dishwasher safe']},
  {id:'oat-throw',name:'Oat linen throw',category:'Textiles',price:168,description:'Washed linen with a little weight to it. Made for shoulders, sofas, and slow Sundays.',image:'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=1000&q=85',details:['100% European linen','55 × 75 in','Machine washable']},
  {id:'arc-board',name:'Arc serving board',category:'Woodwork',price:92,description:'A sculptural serving board cut from a single piece of warm American walnut.',image:'https://images.unsplash.com/photo-1603199506016-b9a594b593c0?auto=format&fit=crop&w=1000&q=85',badge:'New',details:['Solid black walnut','Food-safe finish','18 × 8 in']},
  {id:'dune-vase',name:'Dune bud vase',category:'Ceramics',price:58,description:'A small, tactile silhouette that makes even one stem feel like enough.',image:'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=1000&q=85',details:['Wheel-thrown porcelain','Each one is unique','3.5 in tall']},
  {id:'linen-napkins',name:'Everyday linen napkins',category:'Textiles',price:48,description:'Soft at the edges, durable at the table. A set of four in natural flax.',image:'https://images.unsplash.com/photo-1583845112203-454c7ad4f2c3?auto=format&fit=crop&w=1000&q=85',details:['Set of four','100% linen','18 × 18 in']},
  {id:'pebble-candle',name:'Pebble beeswax candle',category:'Objects',price:28,description:'A hand-poured, unscented candle with a shape borrowed from the shoreline.',image:'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=1000&q=85',details:['Pure beeswax','12 hour burn','Unscented']},
  {id:'still-life',name:'Still life print',category:'Objects',price:76,description:'A quiet archival print for a corner that needs a little more attention.',image:'https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?auto=format&fit=crop&w=1000&q=85',details:['Archival giclée print','12 × 16 in','Unframed']},
  {id:'cedar-scoop',name:'Cedar measuring scoop',category:'Woodwork',price:24,description:'Carved by hand from aromatic cedar, for flour, coffee, or whatever you keep close.',image:'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1000&q=85',details:['Hand-carved cedar','1 tbsp capacity','Made in small batches']},
]
